var DISQUS=function(b,g){function t(a,c){var f=a.length,b=Array.prototype.forEach;if(isNaN(f))for(var r in a)a.hasOwnProperty(r)&&c(a[r],r,a);else if(b)b.call(a,c);else for(b=0;b<f;b++)c(a[b],b,a)}var i=b.document,k=0,u=i.getElementsByTagName("head")[0]||i.getElementsByTagName("body")[0],o={running:!1,timer:null,queue:[]},s={"0.0":{},"1.0":{}},c={config:{},blocks:{theme:{},defaults:{}},status:null,modules:{},settings:{ssl_media_url:"https://securecdn.disqus.com/1312506743",realtime_url:"http://rt.disqus.com/forums/realtime.js",
urls:{unmerged_profiles:"http://disqus.com/embed/profile/unmerged_profiles/"},minify_js:!0,debug:!1,disqus_url:"http://disqus.com",uploads_url:"http://media.disqus.com/uploads",recaptcha_public_key:"6LdKMrwSAAAAAPPLVhQE9LPRW4LUSZb810_iaa8u",media_url:"http://mediacdn.disqus.com/1312506743"}};c.each=t;c.isBrowser=function(a){var c=b.navigator.userAgent,f=/(iPhone|Android|iPod|iPad|webOS|Mobile Safari|Windows Phone)/i;switch(a){case "ie":return/msie/i.test(c)&&!/opera/i.test(c);case "ie6":return!b.XMLHttpRequest;
case "ie7":return/msie/i.test(c)&&!/opera/i.test(c)&&parseInt(/MSIE\s(\d+\.\d+)/.exec(c)[1],10)==7;case "webkit":return~c.indexOf("AppleWebKit/");case "opera":return!(!b.opera||!b.opera.buildNumber);case "gecko":return~c.indexOf("Gecko/");case "mobile":return f.test(c);case "quirks":return i.compatMode==="BackCompat";default:return!1}};c.AssertionError=function(a){this.message=a};c.AssertionError.prototype.toString=function(){return"Assertion Error: "+(this.message||"[no message]")};c.assert=function(a,
d){if(!a)throw new c.AssertionError(d);};c.api=function(a,d){var b=c.comm&&c.comm.Default.recover();if(b){if(!d.type)d.type="GET";if(!d.success)d.success=function(){};if(!d.failure)d.failure=function(){};if(!d.data)d.data={};b.api(a,d.data,d.type,d.success,d.failure)}else c.once("loader.onDefaultChannelReady",function(){c.api(a,d)})};t(["bind","once","unbind","unbindAll","trigger"],function(a){c[a]=function(d,b){var j;d&&(d=d.replace(".","_"));switch(a){case "bind":c.bean.add(c,d,b);break;case "once":j=
function(){c.unbind(d,j);b.apply(this,arguments)};c.bind(d,j);break;case "unbind":c.bean.remove(c,d,b);break;case "unbindAll":c.bean.remove(c,d);break;case "trigger":c.bean.fire(c,d,[b])}}});c.contains=function(a,c){for(var b=0,j=a.length;b<j;b++)if(a[b]==c)return!0;return!1};c.defer=function(a,b){function f(){var a=o.queue;if(a.length===0)o.running=!1,clearInterval(o.timer);try{for(var b=0,d;d=a[b];b++)d[0]()&&(a.splice(b--,1),d[1]())}catch(f){if(!(f instanceof c.AssertionError))throw f;}}o.queue.push([a,
b]);f();if(!o.running)o.running=!0,o.timer=setInterval(f,100)};c.empty=function(a){for(var c in a)if(a.hasOwnProperty(c))return!1;return!0};c.extend=function(){var a,b;arguments.length<=1?(a=c,b=[arguments[0]||{}]):(a=arguments[0]||{},b=Array.prototype.slice.call(arguments,1));c.each(b,function(b){c.each(b,function(c,b){a[b]=c})});return a};c.getGuid=function(){return k++};c.partial=function(){var a=arguments[0],c=Array.prototype.slice.call(arguments,1);return function(){for(var b=Array.prototype.slice.call(arguments),
j=[],e=0,i=c.length;e<i;e++)j.push(c[e]===g?b.shift():c[e]);for(;b.length>0;)j.push(b.shift());return a.apply(this,j)}};c.serializeArgs=function(a){var b=[];c.each(a,function(a,c){b.push(c+(a!==null?"="+encodeURIComponent(a):""))});return b.join("&")};c.serialize=function(a,b,f){b&&(a+=~a.indexOf("?")?a.charAt(a.length-1)=="&"?"":"&":"?",a+=c.serializeArgs(b));if(f)return b={},b[(new Date).getTime()]=null,c.serialize(a,b);b=a.length;return a.charAt(b-1)=="&"?a.slice(0,b-1):a};c.sdk=function(a){function b(d){return function(){function b(e){d!=
e.name||a!=e.version||(e.func.apply({},f),c.unbind("loader.onSDKMethodReady",b))}var f=Array.prototype.slice.call(arguments);c.bind("loader.onSDKMethodReady",b)}}var f=s[a||"1.0"];c.assert(f!==g,"version is not supported.");if(!c.empty(f))return f;c.require(c.settings.media_url+(c.settings.debug?"/js/src/sdk/":"/build/system/sdk/")+a+".js");return{getThread:b("getThread"),getSession:b("getSession")}};c.sdk.add=function(a,b,f){c.assert(s[b]!==g,"version is not supported.");s[b][a]=f;c.trigger("loader.onSDKMethodReady",
{name:a,version:b,func:f})};c.useSSL=function(a){if(b.location.href.match(/^https/)){for(var d=["disqus_url","realtime_url","uploads_url"],a=a||c.settings,f=0,j;j=d[f];f++)a[j]=a[j].replace(/^http/,"https");a.media_url=a.ssl_media_url}};c.useSSL();c.ready=function(a){function b(){var a=c.settings.media_url,d=a+"/js/src/embed/",e=a+"/build/system/",i;c.status="loading";c.settings.debug?(i=a+"/styles/dtpl/defaults.css",a=[d+"dtpl.js",d+"utils.js",d+"sandbox.js",d+"tooltip.js",d+"comm.js",d+"ui.js",
d+"sso.js",d+"compat.js",d+"facebook.js",e+"defaults.js",a+"/js/src/lib/easyxdm.js",a+"/js/src/lib/qwery.js",a+"/js/src/json.js",a+"/js/src/sdk/1.0.js",c.settings.media_url+"/js/src/lib/stacktrace.js"]):(i=e+"/defaults.css",a=[e+"disqus.js"]);c.requireStylesheet(i);c.requireSet(a,c.settings.debug,function(){c.status="ready";c.trigger("loader.onFilesReady")})}if(c.status=="ready")a();else c.once("loader.onFilesReady",function(){a()});c.status===null&&b()};c.require=function(a,b,f,e){function r(a){if(a.type==
"load"||/^(complete|loaded)$/.test(a.target.readyState))e(),c.bean.remove(a.target,o,r)}var g=i.createElement("script"),o=g.addEventListener?"load":"readystatechange";g.src=c.serialize(a,b,f);g.async=!0;g.charset="UTF-8";e&&c.bean.add(g,o,r);u.appendChild(g);return c};c.requireSet=function(a,b,f){var e=a.length;c.each(a,function(a){c.require(a,{},b,function(){--e===0&&f()})})};c.requireStylesheet=function(a,b,e){var j=i.createElement("link");j.rel="stylesheet";j.type="text/css";j.href=c.serialize(a,
b,e);u.appendChild(j);return c};c.addBlocks=function(a,b){if(b)return function(){var a=c.blocks;c.blocks={};b();c.blocks=c.extend(a,{theme:c.blocks})}();var e={Builder:c.strings.Builder,renderBlock:c.renderBlock,each:c.each,extend:c.extend,blocks:c.blocks[a||"defaults"],interpolate:c.strings.interpolate};return function(a){a(e)}};c.renderBlock=function(a,b){var e=a;typeof a==="string"&&(e=c.getBlock(a));if(e===g)throw"Block "+a+" was not found!";return c.sandbox.wrap(a,e,b)};c.getBlock=function(a){return c.blocks.theme[a]||
c.blocks.defaults[a]};c.window={getSize:function(){return typeof b.innerWidth=="number"?[b.innerWidth,b.innerHeight]:i.documentElement?[i.documentElement.clientWidth||i.body.clientWidth,i.documentElement.clientHeight||i.body.clientHeight]:[-1,-1]},getScrollPosition:function(){var a=i.documentElement;return a&&(a.scrollTop||a.scrollWidth)?[a.scrollWidth,a.scrollTop||i.body.scrollTop]:[i.body.scrollWidth,i.body.scrollTop]}};var v={};c.strings={translations:{},setGlobalContext:function(a){c.extend(v,
a)},get:function(a){return c.strings.translations[a]||a},interpolate:function(a,b){var c=[b||{},v];return a.replace(/%\(\w+\)s/g,function(a){a:{for(var a=a.slice(2,-2),b=0,e=c.length;b<e;b++)if(c[b][a]!==g){a=c[b][a].toString();break a}throw"Key "+a+" not found in context";}return a})},pluralize:function(a,b,c){return a!=1?c||"s":b||""},trim:function(a){for(var a=a.replace(/^\s\s*/,""),b=/\s/,c=a.length;b.test(a.charAt(--c)););return a.slice(0,c+1)},capitalize:function(a){return a.charAt(0).toUpperCase()+
a.slice(1)},isUTF8:function(a){for(var b=0,c=a.length;b<c;b++)if(a.charCodeAt(b)>256)return!0;return!1}};var e=function(){this.value=(this.ie=c.isBrowser("ie"))?[]:""};c.strings.Builder=e;e.prototype={put:function(a){this.ie?this.value.push(a):this.value+=a},compile:function(){if(this.ie)this.value=this.value.join("");return this.value}};return c}(this);
(function(b){function g(a){a=a.relatedTarget;if(!a)return a===null;var b;if(b=a!=this)if(b=a.prefix!="xul")if(b=!/document/.test(this.toString())){var c;a:for(a=a.parentNode;a!==null;){if(a==this){c=!0;break a}a=a.parentNode}b=!c}return b}var t=1,i={},k={},u=/over|out/,o=/[^\.]*(?=\..*)\.|.*/,s=/\..*/,c=((b.document||{}).documentElement||{}).addEventListener,v=c?"addEventListener":"attachEvent",e=function(a,b){return a.__uid=b||a.__uid||t++},a=function(a){a=e(a);return i[a]=i[a]||{}},d=c?function(a,
b,c,e){a[e?"addEventListener":"removeEventListener"](b,c,!1)}:function(a,b,c,e,h){h&&e&&(a["_on"+h]=a["_on"+h]||0);a[e?"attachEvent":"detachEvent"]("on"+b,c)},f=function(a,c,e){return function(m){m=x(m||((this.ownerDocument||this.document||this).parentWindow||b).event);return c.apply(a,[m].concat(e))}},j=function(a,b,e,m,h){return function(d){if(m?m.apply(this,arguments):c||d&&d.propertyName=="_on"+e||!d)b.apply(a,Array.prototype.slice.call(arguments,d?0:1).concat(h))}},r=function(b,p,l,m){var h=
p.replace(s,""),q=a(b),q=q[h]||(q[h]={}),i=l,p=e(l,p.replace(o,""));if(q[p])return b;var n=B[h];n&&(l=n.condition?j(b,l,h,n.condition):l,h=n.base||h);l=(n=C[h])?f(b,l,m):j(b,l,h,!1,m);n=c||n;if(h=="unload")var g=l,l=function(){E(b,h,l)&&g()};b[v]&&d(b,n?h:"propertychange",l,!0,!n&&h);q[p]=l;l.__uid=p;l.__originalFn=i;return h=="unload"?b:k[e(b)]=b},E=function(b,p,e){var l;var m,h,q=a(b),f=p.replace(s,"");if(!q||!q[f])return b;l=(p=p.replace(o,""))?p.split("."):[e.__uid],p=l;for(h=p.length;h--;)m=
p[h],e=q[f][m],delete q[f][m],b[v]&&(f=B[f]?B[f].base:f,m=c||C[f],d(b,m?f:"propertychange",e,!1,!m&&f));return b},G=function(a,b,c){return function(e){for(var h=typeof a=="string"?c(a,this):a,d=e.target;d&&d!=this;d=d.parentNode)for(var f=h.length;f--;)if(h[f]==d)return b.apply(d,arguments)}},w=function(a,b,c,e,d){if(typeof b=="object"&&!c)for(var f in b)b.hasOwnProperty(f)&&w(a,f,b[f]);else{f=typeof c=="string";for(var i=(f?c:b).split(" "),c=f?G(b,e,d):c,n=i.length;n--;)r(a,i[n],c,Array.prototype.slice.call(arguments,
f?4:3))}return a},y=function(b,c,e){var d,h,f,i=typeof c=="string",n=i&&c.replace(o,""),g=E,j=a(b);if(i&&/\s/.test(c)){c=c.split(" ");for(f=c.length-1;y(b,c[f])&&f--;);return b}h=i?c.replace(s,""):c;if(!j||i&&!j[h]){if(j&&n)for(d in j)if(j.hasOwnProperty(d))for(f in j[d])j[d].hasOwnProperty(f)&&f===n&&g(b,[d,n].join("."));return b}if(typeof e=="function")g(b,h,e);else if(n)g(b,c);else for(d in g=h?g:y,c=i&&h,h=h?e||j[h]||h:j,h)h.hasOwnProperty(d)&&(g(b,c||d,h[d]),delete h[d]);return b},H=c?function(a,
c,e){evt=document.createEvent(a?"HTMLEvents":"UIEvents");evt[a?"initEvent":"initUIEvent"](c,!0,!0,b,1);e.dispatchEvent(evt)}:function(a,b,c){a?c.fireEvent("on"+b,document.createEventObject()):c["_on"+b]++},F=function(b,c,d){var f=a(c),h;e(b);f=d?f[d]:f;for(h in f)f.hasOwnProperty(h)&&(d?w:F)(b,d||c,d?f[h].__originalFn:h);return b},x=function(a){var b={};if(!a)return b;var c=a.type,e=a.target||a.srcElement;b.preventDefault=x.preventDefault(a);b.stopPropagation=x.stopPropagation(a);b.target=e&&e.nodeType==
3?e.parentNode:e;if(~c.indexOf("key"))b.keyCode=a.which||a.keyCode;else if(/click|mouse|menu/i.test(c)){b.rightClick=a.which==3||a.button==2;b.pos={x:0,y:0};if(a.pageX||a.pageY)b.clientX=a.pageX,b.clientY=a.pageY;else if(a.clientX||a.clientY)b.clientX=a.clientX+document.body.scrollLeft+document.documentElement.scrollLeft,b.clientY=a.clientY+document.body.scrollTop+document.documentElement.scrollTop;u.test(c)&&(b.relatedTarget=a.relatedTarget||a[(c=="mouseover"?"from":"to")+"Element"])}for(var d in a)d in
b||(b[d]=a[d]);return b};x.preventDefault=function(a){return function(){a.preventDefault?a.preventDefault():a.returnValue=!1}};x.stopPropagation=function(a){return function(){a.stopPropagation?a.stopPropagation():a.cancelBubble=!0}};var C={click:1,dblclick:1,mouseup:1,mousedown:1,contextmenu:1,mousewheel:1,DOMMouseScroll:1,mouseover:1,mouseout:1,mousemove:1,selectstart:1,selectend:1,keydown:1,keypress:1,keyup:1,orientationchange:1,touchstart:1,touchmove:1,touchend:1,touchcancel:1,gesturestart:1,gesturechange:1,
gestureend:1,focus:1,blur:1,change:1,reset:1,select:1,submit:1,load:1,unload:1,beforeunload:1,resize:1,move:1,DOMContentLoaded:1,readystatechange:1,error:1,abort:1,scroll:1},B={mouseenter:{base:"mouseover",condition:g},mouseleave:{base:"mouseout",condition:g},mousewheel:{base:/Firefox/.test(navigator.userAgent)?"DOMMouseScroll":"mousewheel"}},D={add:w,remove:y,clone:F,fire:function(b,c,e){var d,f,i=c.split(" ");for(f=i.length;f--;){var c=i[f].replace(s,""),j=C[c],g=i[f].replace(o,""),k=a(b)[c];if(g){g=
g.split(".");for(d=g.length;d--;)k&&k[g[d]]&&k[g[d]].apply(b,[!1].concat(e))}else if(!e&&b[v])H(j,c,b);else for(d in k)k.hasOwnProperty(d)&&k[d].apply(b,[!1].concat(e))}return b}};b.attachEvent&&w(b,"unload",function(){for(var a in k)if(k.hasOwnProperty(a)){var c=y(k[a]).__uid;c&&(delete k[c],delete i[c])}b.CollectGarbage&&CollectGarbage()});var I=b.bean;D.noConflict=function(){b.bean=I;return this};typeof module!=="undefined"&&module.exports?module.exports=D:b.bean=D})(this);
DISQUS.extend({bean:bean.noConflict(),debounce:function(b,g,t,i){var k;DISQUS.bean.add(b,g,function(b){k&&clearTimeout(k);k=setTimeout(function(){t(b)},i)})}});DISQUS.addJob=DISQUS.defer;DISQUS.getResourceURL=DISQUS.serialize;DISQUS.lang={contains:DISQUS.contains,forEach:DISQUS.each,extend:DISQUS.extend,trim:DISQUS.strings.trim,partial:DISQUS.partial};DISQUS.events={add:DISQUS.bean.add,remove:DISQUS.bean.remove,debounce:DISQUS.debounce};
DISQUS.browser={ie:DISQUS.isBrowser("ie"),ie6:DISQUS.isBrowser("ie6"),ie7:DISQUS.isBrowser("ie7"),webkit:DISQUS.isBrowser("webkit"),opera:DISQUS.isBrowser("opera"),gecko:DISQUS.isBrowser("gecko"),mobile:DISQUS.isBrowser("mobile"),quirks:DISQUS.isBrowser("quirks")};
(function(b){function g(a,b){return a.hasAttribute?a.hasAttribute(b):a.getAttribute(b)!==null}function t(){for(var a=0,b=A.length;a<b;a++)if(g(A[a],"name")&&A[a].getAttribute("name")=="generator"&&g(A[a],"content")&&A[a].getAttribute("content")=="blogger")return!0;a=e.getElementById("Attribution1");if(a!==null&&a.innerHTML.indexOf("http://www.blogger.com")>0)return!0}function i(){var a;if(t()){a=e.getElementsByTagName("A");for(var b=0,c=a.length;b<c;b++)if(!g(a[b],"src")&&g(a[b],"name")&&parseInt(a[b].getAttribute("name"),
10)&&a[b].innerHTML==="")return a[b].getAttribute("name")}return null}function k(a){var b=0,c=0;if(!a.offsetParent)return[0,0];do b+=a.offsetLeft,c+=a.offsetTop,a=a.offsetParent;while(a);return[b,c]}function u(b){var c=a.window.getScrollPosition()[1],e=c+a.window.getSize()[1];return b>=c&&b<=e}function o(){var c=b.location.href,z=b.location.hash,g=f||{};a.extend(a.config,{container_id:w||"disqus_thread",page:{url:Q||c,title:P||"",sort:n||"",per_page:l||null,category_id:G||"",developer:+B,identifier:p||
""},trackback_url:g.trackback_url||null,trackbacks:g.trackbacks||null,absorbStyles:!1});c=e.getElementById(a.config.container_id);g=k(c)[1];if(c&&u(g))a.config.page.lazy="0";if(t())a.config.page.blogger_id=i(),a.config.page.url=a.config.page.url.replace(/\?.*$/,"");if(typeof h!="undefined")a.config.page.require_mod_s=h;if(typeof m!="undefined")a.config.page.remote_auth_s2=m;if(typeof j!="undefined")a.config.page.author_s2=j;if(typeof l!="undefined")a.config.page.per_page=l;if(typeof K!="undefined")a.config.page.slug=
K;if(z&&(z=z.match(/comment\-([0-9]+)/)))a.config.page.anchor_post_id=z[1];a.config.callback_params=E||null;typeof r=="function"&&a.bind("thread.onReady",function(){r(a.config.callback_params)});if(typeof y=="object")a.config.custom_strings=y;a.extend(a.config,{domain:D||(C?"dev.disqus.org":"disqus.com"),shortname:q||a.getShortname(),facebook_forum:I||null,facebook_key:N||null,def_name:F,def_email:H,def_text:x||"",skip_auth:O||!1});z=a.config.shortname+"."+a.config.domain+"/thread.js";a.config.json_url=
b.location.href.match(/^https/)?"https://"+z:"http://"+z;(function(){if(typeof b.disqus_config=="function"){var c={preData:"loader.onReady",preInit:"loader.onDataReady",onInit:"loader.onLibraryReady",afterRender:"loader.onTemplateReady",onReady:"thread.onReady",onPaginate:"thread.onPaginate",onNewComment:"comment.onCreate",preReset:"thread.beforeReset"};a.config.callbacks={};a.each(c,function(b,c){a.config.callbacks[c]=[]});try{d.call(a.config)}catch(e){}a.each(a.config.callbacks,function(b,e){b.length!==
0&&a.each(b,function(b){a.bind(c[e],b)})});a.config.callbacks=c}})()}function s(){function b(a,c,e,d,f,L){return"<"+["img",'width="'+a+'"','height="'+c+'"','alt="'+d+'"','src="data:image/'+e+";base64,"+f+'"',L?'style="'+L+'"':""].join(" ")+"/>"}a.jsonData={ready:!1};a.require(a.config.json_url,a.config.page,!0);var c=e.getElementById("dsq-content")||e.createElement("div");c.id="dsq-content";c.style.display="none";var d=e.getElementById("dsq-content-stub")||e.createElement("div");d.id="dsq-content-stub";
d.innerHTML=a.browser.ie6?"...":b(71,17,"png","DISQUS",R.join(""))+b(16,11,"gif","...",S.join(""),"margin:0 0 3px 5px");var f=e.getElementById(a.config.container_id);f.appendChild(c);f.appendChild(d);a.ready(function(){a.initThread(function(){d.style.display="none"})})}function c(c){var d=e.getElementById("dsq-content"),f=a.settings.media_url+"/build/system/",h=a.settings.media_url+"/build/lang/",g=a.jsonData.forum.template.css,i=a.jsonData.forum.template.url,j=a.jsonData.context.switches;(function(){var b=
a.jsonData;a.strings.setGlobalContext({profile_url:b.urls.request_user_profile,disqus_url:b.settings.disqus_url,media_url:b.settings.media_url,forum_name:b.forum.name,request_username:b.request.username,request_display_username:b.request.display_username})})();a.trigger("loader.onDataReady");if(a.browser.mobile&&!a.jsonData.forum.mobile_theme_disabled)g=a.jsonData.forum.template.mobile.css,i=a.jsonData.forum.template.mobile.url;else if(a.config.template)g=a.config.template.css,i=a.config.template.js;
!b.disqus_no_style&&g&&a.requireStylesheet(g,{},a.jsonData.settings.debug);g=a.jsonData.forum.stylesUrl;if(!a.jsonData.context.switches.static_styles||a.settings.debug)g="http://"+a.config.domain+"/forums/"+a.config.shortname+"/styles.css";a.jsonData.forum.hasCustomStyles&&a.requireStylesheet(g,{u:a.jsonData.forum.lastUpdate});i=[i];j.new_toolbar&&(i.push(f+"/defaults.toolbar.js"),f=a.settings.debug?a.settings.media_url+"/styles/dtpl/defaults.toolbar.css":f+"/defaults.toolbar.css",a.requireStylesheet(f,
{},a.jsonData.settings.debug));f=b.location.search;~f.indexOf("fbc_channel=1")?a.require("http://static.ak.connect.facebook.com/js/api_lib/v0.4/FeatureLoader.js.php"):~f.indexOf("fb_xd_fragment")?a.require("http://connect.facebook.net/en_US/all.js"):(a.config.language?a.config.language!="en"&&i.push(h+a.config.language+".js"):a.jsonData.forum.language!="en"&&i.push(h+a.jsonData.forum.language+".js"),a.comm.Default.create(function(){a.trigger("loader.onDefaultChannelReady")}).setApiKey(a.jsonData.forum.apiKey),
a.requireSet(i,a.jsonData.settings.debug,function(){a.config.custom_strings&&a.lang.extend(a.strings.translations,a.config.custom_strings);if(a.config.def_text==="")a.config.def_text=a.strings.get("Type your comment here.");a.registerActions();a.trigger("loader.onActionsReady");a.nodes.addClass(d,"clearfix");var b=d.parentNode;b.removeChild(d);d.innerHTML=a.renderBlock("thread");b.appendChild(d);a.trigger("loader.onLibraryReady");a.dtpl.actions.fire("thread.initialize");a.trigger("loader.onTemplateReady");
a.bean.add(d,"click change",function(b){for(var c=b.target,e;c!=d;){if(e=a.dtpl.getAction(c,b)){b.preventDefault();e();break}c=c.parentNode}});a.nodes.container=a.nodes.get("#dsq-content");d.style.display="block";c();a.config.page.anchor_post_id&&a.nodes.scrollTo("#dsq-comment-"+a.config.page.anchor_post_id);a.dtpl.actions.fire("thread.ready")}))}function v(a){return Date.UTC(a.getUTCFullYear(),a.getUTCMonth(),a.getUTCDate(),a.getUTCHours(),a.getUTCMinutes(),a.getUTCSeconds(),a.getUTCMilliseconds())}
var e=b.document,a=b.DISQUS,d=b.disqus_config,f=b.DsqLocal,j=b.disqus_author_s2,r=b.disqus_callback,E=b.disqus_callback_params,G=b.disqus_category_id,w=b.disqus_container_id,y=b.disqus_custom_strings,H=b.disqus_def_email,F=b.disqus_def_name,x=b.disqus_default_text,C=b.disqus_dev,B=b.disqus_developer,D=b.disqus_domain,I=b.disqus_facebook_forum,N=b.disqus_facebook_key,p=b.disqus_identifier,l=b.disqus_per_page,m=b.disqus_remote_auth_s2,h=b.disqus_require_moderation_s,q=b.disqus_shortname,O=b.disqus_skip_auth,
n=b.disqus_sort,K=b.disqus_thread_slug,P=b.disqus_title,Q=b.disqus_url;e.getElementsByTagName("head")[0]||e.getElementById("disqus_thread");var A=e.getElementsByTagName("meta"),J=!1,R=["iVBORw0KGgoAAAANSUhEUgAAAEcAAAARCAYAAAH4YIFjAAAAGXRFWHRTb2Z0d2FyZQBB","ZG9iZSBJbWFnZVJlYWR5ccllPAAABwdJREFUeNpi/P//PwMhwAIiGBkZGeK6V8JVh9rq","dfrc0ixnEDb+wPD2rAAjMSYBBBBRisDWwKxCthIE/q8Q+A8yhCiTAAIIrCi+ZxVMZSAQ","r19UGs4IMxWd/X8Rw3/GOKDhW43fgzwF1hX7n5EJ2dSp2QFNUKcZwJ31/78CkvPBGkGG","MXidSUTWCxBAxAUAEQAcJzCvIXsDBPwsNBU2nbj+AMpdsFA8PAHsLZj3QC5D9hrIAEtN",
"+RMwAzRkxcB0iK3eQ6iQIRAnoMTE//8CyHwmWHQdv/7QAiZ44/ErMP383acsqNB5iMnP","lsFdsUZ6IU3CCCCA4AYBw8kBJgj06gGkmHJAFgPyQV4ExeQEoNgHJHUBQMoAWRzoerBe","YHgeQOJ/APIvQPkNUP4EuIdADBAGBRMQOABxQcakdSipHZldNGvL2zWHL8kD1d0HieVN","33QYqnc/EAfULNwJVw8KTniQwvjAdPz/SEwKmL1KfC5QjwEQr4e5AyVdA3P4ASCe8O3n","b1whmtib6r3IXlfpATBEFbpWH9ygJSdmBtXrOHPbyZWPXn1AqOZRwDSBS+YHo82SOQwi","ZnYMoS+EGC42nGdYzBiAnKpgGAbeA3ECkjwYQNnzH758///6o5cgofVIagy+/vgFF//y","/ecHJLn1/18AA+/teZBcPZL4eSTxBJg7AAKIaomRmpkeV2IG5UcDpMSsAM2zF4BiG9DU","FaCLQxPwBWCC/QBkg/QqoCVuEN4ASuDIaWc/DIMSItBxH0GCrkaqCVBxWO4BJWBQcK/P",
"mrL+I1S8H0i9h4mjFfX7GTRyIdEuHzIfZtb/Zdw3oGyQnvP/d9pNgRc+MLCwJMxxWk7A","I6Ar+YCWVSLLyYkJzIYlZqC6RGBhbg/lFwDlQHoDgfgALLfhjY8/X9XhpWPs/wWM7ody","MBwDylU8nOzyILYIH3cZslxBgM0cKHM+MOTAGCZnri7XCdS7ASgGLsc/fPlug9cxlrO/","wUvYxYwJwCgLwHAMcrVlqCJ9BVlchJ+7EhRyQPwAyGaAFnhgsOPMzUhQroLVAU76yp/g","Gp/vtQbTr45pwMWOp1oDQ6QQiGEi6+EJGLmah0YJQ6CVtu3ivecKYHIpE9b8BPqcDSna","wHSSu8m3eTvPyAHlzsPkDl25/wXMYAOq+XgtBFwIfn/GwCAOSq8HYCGCsNh8+hvksgYZ","IJchDkjljAKoHAKVJ6ByBbnmA5XESOL1oFIZSc9/cJkC1IukPuH/z/cw8fswdwyqcgYg","wAaVYwYbQEnDSI1LbGABEDcCC1lYS4yhfO42n+fvPm9GKsAZkfJDA7RcwwYmQM1CbpUU",
"ADU3AB3AjxJ7wFwAFGsAqp2A0mBDahww8Gv4Mvrf2AKXWyMzgeHbk3wwh5X/DGPkR1Oo","HlCmn49cGCABkL8SgZn8ANbAQQaV4ZBK6yGwgbDr3G2GNx+/gkqShMTe1V///vsnA/KY","joKECjBwMPQCW0EngOrNQWxbHQWGFA8zBlAj5eztpwwbjl9lyPG1DFOUEAIFDqxJB6ks","oC1ZN2NVsDm7zt4GNUhBgdUPrXwckWtQOJB0VQE2XRF8UQt9hodrIGw+FaDcWVjAwAsh","hsD7kAbPO2Dr78ZEBoZfHxQYHNYbwEogvIGjKSfOiNysBpaEL/acv8MODBhuUX7u00Bh","VVx6DZWlxHcDAxQEDl95AMZQAGqHLlSSFIanAnZWll0/f/8Bs2OcDB+5GavJVyGZtevs","rYdL9p2XQ6rZGcnKI54nZRj2uoMCAVr4K8JkQAKgJsdEYN12AbmYYSGqYGJk/NC8bO91","WHKUFRXgwace6ElDIF4PjHWHc3eeMZy98xSU8mB1mwE0FSQCU8ECZiZGVpi+yw9eLIfV",
"lUyMjIf+/f/Pu/bIlTtIdSX5hauo+RagxxMZfr2fwHB3IT/Dy4MMDI/BzTABaP2aAGzm","gPpN4gQDB1pmgIA+EAfcfvoGXl/mB1hXFuBxCLDs6oc26kBJZiIoxShLCqs9e/tp+vdf","v8ENB08Tdf9FwHKsMtxxTfvK/SGgbHfx3vNyoL2g7DjR30r74vqjV2yA6lXgbnI2WtoH","4yhEfGF4sAISSTcm9wOzDcidoE6lPTBLwRuyDMoJ5+DZagnLJIb/f3mh5edGcKoRs+5n","eHUUUgZxiIrhrK2wFchc7KwMmsByANjiAZUfoGzhCEpJIDlQowOYffqRC2RQS+f1x68H","Nx6/ygcqY9A7RMZAc5LcTS/zcLLZwcwB1evAzs/8pfsvwDu9yOplgRECzF4M8a7Gryw0","5NRB+sDtiC/3HjKcKeaDpgAEADVmNIDlsX4DqFPmCOvvMNxdkAAuX95dQFUPKnv06kEB","mQgNOLpV5QbQpAsrcz4QUC+AVJsgqxcgoNcBqQy5QIIdONUDALcn6c0dtMJ9AAAAAElF",
"TkSuQmCC"],S=["R0lGODlhEAALAPQAAP///z2LqeLt8dvp7u7090GNqz2LqV+fuJ/F1IW2ycrf51aatHWs","waXJ14i4ys3h6FmctUCMqniuw+vz9eHs8fb5+meku+Tu8vT4+cfd5bbT3tbm7PH2+AAA","AAAAAAAAACH/C05FVFNDQVBFMi4wAwEAAAAh/hpDcmVhdGVkIHdpdGggYWpheGxvYWQu","aW5mbwAh+QQJCwAAACwAAAAAEAALAAAFLSAgjmRpnqSgCuLKAq5AEIM4zDVw03ve27if","DgfkEYe04kDIDC5zrtYKRa2WQgAh+QQJCwAAACwAAAAAEAALAAAFJGBhGAVgnqhpHIeR","vsDawqns0qeN5+y967tYLyicBYE7EYkYAgAh+QQJCwAAACwAAAAAEAALAAAFNiAgjoth","LOOIJAkiGgxjpGKiKMkbz7SN6zIawJcDwIK9W/HISxGBzdHTuBNOmcJVCyoUlk7CEAAh",
"+QQJCwAAACwAAAAAEAALAAAFNSAgjqQIRRFUAo3jNGIkSdHqPI8Tz3V55zuaDacDyIQ+","YrBH+hWPzJFzOQQaeavWi7oqnVIhACH5BAkLAAAALAAAAAAQAAsAAAUyICCOZGme1rJY","5kRRk7hI0mJSVUXJtF3iOl7tltsBZsNfUegjAY3I5sgFY55KqdX1GgIAIfkECQsAAAAs","AAAAABAACwAABTcgII5kaZ4kcV2EqLJipmnZhWGXaOOitm2aXQ4g7P2Ct2ER4AMul00k","j5g0Al8tADY2y6C+4FIIACH5BAkLAAAALAAAAAAQAAsAAAUvICCOZGme5ERRk6iy7qpy","HCVStA3gNa/7txxwlwv2isSacYUc+l4tADQGQ1mvpBAAIfkECQsAAAAsAAAAABAACwAA","BS8gII5kaZ7kRFGTqLLuqnIcJVK0DeA1r/u3HHCXC/aKxJpxhRz6Xi0ANAZDWa+kEAA7","AAAAAAAAAAAA"];
a.extend({cache:{postboxBusy:{},buttonsToRestore:[],popupProfileCache:{},popupStatusCache:{},toggledReplies:{},postSharing:{},realtime:{interval:null,ongoing_request:null,prev_script:null,last_checked:null,newPosts:[]}},states:{edit:{},realtime:!1,useLoginWindow:!1,loginDisabled:!1,metaViewport:function(){for(var a=0,b=A.length;a<b;a++)if(A[a].getAttribute("name")=="viewport")return!0;return!1}()},curPageId:"dsq-comments",frames:{},config:{template:null},jsonData:null,isReady:!1,getShortname:function(){function a(b){var b=
b.getAttribute?b.getAttribute("src"):b.src,c=[/https?:\/\/(www\.)?disqus\.com\/forums\/([\w_\-]+)/i,/https?:\/\/(www\.)?([\w_\-]+)\.disqus\.com/i,/https?:\/\/(www\.)?dev\.disqus\.org\/forums\/([\w_\-]+)/i,/https?:\/\/(www\.)?([\w_\-]+)\.dev\.disqus\.org/i],d=c.length;if(!b||b.substring(b.length-8)!="embed.js")return null;for(var e=0;e<d;e++){var f=b.match(c[e]);if(f&&f.length&&f.length==3)return f[2]}return null}for(var b=e.getElementsByTagName("script"),c=b.length-1;c>=0;c--){var d=a(b[c]);if(d!==
null)return d}return null},callback:function(b){var c=arguments.length>1?Array.prototype.slice.call(arguments,1):[];a.trigger(b,{args:c})},reset:function(b){var c=a.nodes.get("#"+a.config.container_id),b=b||{};a.comm.reset();a.jsonData=null;a.sandbox.invalidateGlobals();a.status=null;c.innerHTML="";a.trigger("thread.beforeReset");a.unbindAll();if(b.reload){o();if(b.config)try{b.config.call(a.config)}catch(d){}s()}},updatePost:function(b,c){var d=a.jsonData.posts[b]||{};if(c)c.id=b,a.jsonData.posts[b]=
a.extend(d,c),a.trigger("data.onPostUpdate",{id:b,data:c})},reload:function(b){a.require(a.config.json_url,a.config.page,!0,function(){J=!0;typeof b=="function"&&b()})},redraw:function(b){if(J||b)a.sandbox.invalidateGlobals(),b=a.nodes.get("#dsq-content"),b.innerHTML=a.renderBlock("thread"),a.frames=[],a.dtpl.actions.fire("thread.initialize"),J=!1},initThread:function(d){function f(a){var c=b.onload;b.onload=typeof b.onload!="function"?a:function(){c&&c();a()}}function i(){var c,d;if(a.isReady){if(h&&
clearInterval(h),e.getElementById(w),c=e.getElementsByTagName("iframe"),d=e.getElementById("dsq-content"))for(var f=0,g=c.length;f<g;f++)c[f].style.width=d.offsetWidth}else h||(h=b.setInterval(i,500))}var g,h;a.browser.ie&&a.config.frame_theme!=="cnn2"&&f(i);a.trigger("loader.onReady");g=e.getElementById("dsq-content")||e.createElement("div");g.id="dsq-content";g.style.display="none";e.getElementById(a.config.container_id).appendChild(g);a.container=e.getElementById("dsq-content");try{a.browser.ie6&&
e.execCommand("BackgroundImageCache",!1,!0)}catch(j){}a.config.page.lazy="0";var k=a.partial(c,d),l=a.partial(a.require,a.config.json_url,a.config.page,!0,k);if(a.jsonData==null)return void l();a.defer(function(){var b=a.jsonData;return b&&(b.ready||b.lazy)},function(){if(a.jsonData.ready)return void k();a.once("disqus.viewed",function(){l()})})}});o();s();(function(){function c(){d&&u(f)&&a.trigger("disqus.viewed")}var d=e.getElementById(a.config.container_id),f=k(d)[1];c();a.events.debounce(b,"scroll",
c,250)})();a.bind("thread.onReady",function(){function c(){f&&u(f)&&a.trigger("comments.reply.viewed");g&&u(g)&&a.trigger("comments.viewed")}var d=e.getElementById("dsq-reply")||e.getElementById("dsq-new-post"),f=d?a.nodes.getPosition(d)[1]+d.offsetHeight:null,d=e.getElementById("dsq-comments"),g=a.nodes.getPosition(d)[1]+d.offsetHeight;c();a.events.debounce(b,"scroll",c,250)});var M=v(new Date);a.bind("thread.onReady",function(){var c=a.comm.Default.recover(),d=v(new Date);c.log("load:start",M);
c.log("load:length",d-M);try{b.jQuery?c.log("jslib","jquery:"+jQuery().jquery):b.jQuery&&jQuery.ui?c.log("jslib","jqueryui:"+jQuery.ui.version):b.Prototype?c.log("jslib","prototype:"+Prototype.Version):b.dojo?c.log("jslib","dojo:"+dojo.version.toString()):b.MooTools?c.log("jslib","mootools:"+MooTools.version):b.Ext?c.log("jslib","ext:"+Ext.version):b.YUI?c.log("jslib","yui:"+YUI.version):c.log("jslib","none")}catch(e){c.log("jslib","error")}try{b.FB&&FB.dynData&&c.log("oldfb","true")}catch(f){}c.flushLog(null)});
a.bind("loader.onTemplateReady",function(){var b=a.comm.Default.recover(),c=a.jsonData;c.context.switches.sigma&&b.enable(c.context.sigma_chance);b.log("hit",1);c.forum.id&&b.addMeta("info:forum_id",c.forum.id);c.thread.id&&b.addMeta("info:thread_id",c.thread.id);c.request.user_type&&b.addMeta("info:user_type",c.request.user_type);c.request.user_id&&b.addMeta("info:user_id",c.request.user_id)});a.once("comments.viewed",function(){a.comm.Default.recover().log("viewed:comments",1)});a.once("comments.reply.viewed",
function(){a.comm.Default.recover().log("viewed:comment_box",1)})})(this);
